services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Init Listener
    acilia.translation.listener.init:
        class: Acilia\Bundle\TranslationBundle\EventListener\InitListener
        arguments:
            $loader: '@acilia.translation.loader'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: initialize, priority: 16 }
            - { name: kernel.event_listener, event: console.command, method: initialize, priority: 16 }

    # Translation Loader
    acilia.translation.loader:
        class: Acilia\Bundle\TranslationBundle\Library\Translation\Loader

   # Translations Cache Warmer
    acilia.translation.cache_warmer:
        class: Acilia\Bundle\TranslationBundle\Library\Translation\CacheWarmer
        arguments:
            $loader: '@acilia.translation.loader'
        tags:
            - { name: kernel.cache_warmer }
